### PR TITLE
News carousel

### PR DESCRIPTION
**Pull request by ronald-bbg**
Updated news section data feed from json integrated with owl-carousel styles 

We also will need 4 or more tiles for the carousel to show arrows -> since if 3 tiles to be shown, arrows will disappear (pending additional news data...)

https://victorious-forest-0afabf510-5.centralus.3.azurestaticapps.net/

### CODE REVIEW

**Review by will-wbd — CHANGES_REQUESTED** [review]
- Please double check font sizes and headings. The text seems off with respect to the mockup
- The card shadows seem to be cut off
- Control buttons do not appear to be the same size as in the mockup
- At tablet-lg and desktop, the section does not appear to span 100% width. See screenshot
Screenshot 2023-08-18 at 10 50 01 AM
- At mobile or mobile-lg, the fonts are very large. See screenshot below
- At mobile or mobile-lg, reduce the cards to show just two at a time. In its current state, three is too many and does not lend well to readability . See screenshot below
mobile-lg
- Diffusion has more than 3 articles. Please view their live site for the articles

**Comment by ronald-bbg** [comment]
articles for reference: https://www.innovation.va.gov/ecosystem/views/diffusion-excellence/doe.html

**Review by will-wbd — CHANGES_REQUESTED** [review]
- The font sizes don't seem to be matching the mockup. May I ask why we're using "font-size: calc(1rem + .9vw)!important;" rather than the default font-size of the h4 ? 
- Container of the News & Events section does not line up with the container of the footer. See screenshot
Screenshot 2023-08-23 at 9 32 06 AM
- Button size do not match mockup. The size should resemble 48x48 
Screenshot 2023-08-23 at 9 33 36 AM
- Cards to not appear to be the same height. Let's try to make them the same height. Not necessarily cut off content/description but adjust the height of the card.
Screenshot 2023-08-23 at 9 33 49 AM

**Comment by ronald-bbg** [comment]
thanks for the notes @will-wbd! I think the scaling font-size for h4 was to use a universal font size that works for tablet all the way up but because the container was set to match the width of the blue programs background, we may be able to use the default h4 font-size once the container matches the footer section...will adjust the rest....more to come, thanks!

**Review by will-wbd — APPROVED** [review]

**Pull request merged**
