### PR TITLE
rp-subnav

### PR DESCRIPTION
**Pull request by ronald-bbg**

### CODE REVIEW

**Comment by ecstech-admin** [comment]
AWESOME! Great progress.

Needs some sort of visual in mobile to let user know there's hidden options (plus sign or down chevron to click on to open/close) similar to what's available in USWDS 2.x

Visual cue also needed for desktop, etc., to let user know pages beneath "About" and "Portfolios and Programs" (again, similar to what's on USWDS 2.x)

image

Need to add "Talent Accelerator" to DoE subnav

Otherwise, looks good.

Need to add "Talent Accelerator" to DoE subnav

**Review by will-wbd — CHANGES_REQUESTED** [review]
Nice work, Ronald.

I have a few changes:
* Menu does not disappear when I hover over another link
Screenshot 2023-10-03 at 10 30 53 AM
* When active, a gap to the top level is added 
Screenshot 2023-10-03 at 10 31 28 AM

**Comment by ronald-bbg** [comment]
PR fixes addressed!

**Review by will-wbd — CHANGES_REQUESTED** [review]
* The top nav items jump when hovering on items in dropdown that have a subnav. See video.

https://github.com/WBDynamics/VA-DOE/assets/134664107/5a36214c-e03f-43dd-9c79-d7336ffd958c
* Please use same style of arrow that is used in the top level
Screenshot 2023-10-05 at 7 48 32 AM

**Comment by ronald-bbg** [comment]
weird - added a fix for the jumping/expanding button dropdown on my end prior to the re-review...this is what I have for the fix 

I'll update the arrow styles...
https://github.com/WBDynamics/VA-DOE/assets/137827146/c7b9306a-d4bd-4566-ac19-bf028984b76c

**Comment by will-wbd** [comment]
I cleared browser cache and the jumping is no longer there.

**Review by will-wbd — APPROVED** [review]

**Pull request merged**
