### PR TITLE
made WE button & text color fix for 508 compliancy

### PR DESCRIPTION
**Pull request by ronald-bbg**

### CODE REVIEW

**Review by ecstech-admin — APPROVED** [review]
Good to go!

**Review by will-bbg — CHANGES_REQUESTED** [review]
@ronald-bbg did you replace design elements and change the blue in the masthead background? 

If so, revert the design elements you changed back to the initial color. The ticket was just to replace the button background and text color. Those of which are are not compliant, not the design elements.

**Review by will-bbg — CHANGES_REQUESTED** [review]
View screenshot below - background gradient still doesn't look like what is on live. 

Screenshot 2023-12-20 at 8 24 48 AM

**Review by will-bbg — APPROVED** [review]
👍🏽

**Pull request merged**
