### PR TITLE
Jls fix font paths

### PR DESCRIPTION
**Pull request by ecstech-admin**
edit font path in _site/assets/sass/_uswds-theme.scss
rm duplicate fonts dir and contents
adjust spacing on nav dropdowns
clean up code: rm commented out content

### CODE REVIEW

**Comment by ecstech-admin** [comment]
Myriad Pro added to /uswds/fonts/
Myriad Pro styled in font.scss
rm all .ttf fonts
reset css location for nav arrow

**Review by ronald-bbg — APPROVED** [review]
looks good!

**Comment by ecstech-admin** [comment]
Cleaned up repo by removing unused fonts
Edited sass/vha/content/fonts.scss to include .woff versions of Source Sans Pro fonts (styles only links to .woff2)

**Comment by ronald-bbg** [comment]
looks good! looks like you just need to resolve a couple conflicts for the merge

**Pull request merged**
