### PR TITLE
feature/rl-6646398254/add-video-to-doe-image

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [X] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Update DOE Homepage with link to video over main image

## Related Tickets & Documents
- Monday Task #6646398254
- https://blackberg-group.monday.com/boards/1931719392/pulses/6646398254

-verify main image acts as a link to a popup youtube video
-video should be: https://www.youtube.com/watch?v=uuVKWt8HIpc
-page should resize with same layout as before

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

### CODE REVIEW

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/ecosystem/views/diffusion-excellence/index.html

**Review by will-bbg — DISMISSED** [review]
Looks like we are using the same hero image as before the request.

Since we are linking to a new video, please grab a screenshot from the video that illustrates the message and use it as the hero image.

**Comment by RyanCrux** [comment]
Alec asked to use the same image.

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
