### PR TITLE
Feat/rl 7505148368/diffusion website edits

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

DOE page edits

## Related Tickets & Documents
- Monday Task: https://blackberg-group.monday.com/boards/1931719392/pulses/7505148368

## QA Instructions, Screenshots, Recordings

- Review layout/ design adjustments to match with word doc requests linked in monday ticket
- Test page mechanics 
- Review copy edits match word document 

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized 

## Changed Files in this Pull Request ##
- _includes/home/doe-mission.html
 - _includes/home/doe-playbook.html
 - _includes/home/programs.html
 - _site/assets/css/styles.css
 - _site/assets/sass/vha/pages/home/programs/_index.scss
 - _site/index.html
 - assets/css/styles.css
 - assets/sass/vha/pages/home/programs/_index.scss
 - index.html

### CODE REVIEW

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/ecosystem/views/diffusion-excellence/

**Review by will-bbg — CHANGES_REQUESTED** [review]
**New Content Updates** 

1. Since the Diffusion Playbook and (new) Diffusion Marketplace sections have Content (left) and Image (right), let's switch up the content layouts. 
- Please make Diffusion Marketplace layout to be Image (left) and Content (right). 

2. Diffusion of Excellence programs section
- The spacing between each section needs some clean up. As specified in the ticket, please remove all of the "wonky" custom, non-uswds classes. That includes the margins by percentages. Such as, ".margin-top-8p", "margin-top-m26p" and replace with UWDS margin classes.
- Double check spacing for tablet and mobile devices as the current margins are too small and doesn't allow for clarity as far as to when a section ends and the next begins. Please see https://dev-innovation.bgsandbox.com/ecosystem/views/diffusion-excellence/sharktank/ for inspiration on mobile spacing.

3. Diffusion Academy needs some cleaning up. The lop sided section just does not flow with the rest of the page. 
- I have created a mockup for this section. This will be for tablet-lg and up tablet and down will be stacked. 
Screenshot 2024-10-14 at 3 23 50 PM

4. News and Events section is missing the new articles. 
Screenshot 2024-10-14 at 8 02 04 AM

**Layout Updates that currently exist**
1. I do not know why this blue section extends past the USWDS container but let's fix that. Make the blue container fit within the ".grid-container". 
Screenshot 2024-10-14 at 3 26 40 PM

2. Hopefully this is a product from above but on desktop/tablet-lg the blue section is smaller than the USWDS container. Let's fix that. 
Screenshot 2024-10-14 at 3 27 38 PM

3. On "tablet-lg", I am not a fan of how tiny these images are. Please make the sections span 100% of the width on "tablet-lg" and down. 
Screenshot 2024-10-14 at 3 29 04 PM

4. Please double check that there is just ONE h1 on the page. That should be "Replicating and Scaling Promising Practices". All the other h1's need to h2 with the ".h1" class attached for font size. Thank you.

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/ecosystem/views/diffusion-excellence/


New Content Updates
1. Since the Diffusion Playbook and (new) Diffusion Marketplace sections have Content (left) and Image (right), let's switch up the content layouts.
* Please make Diffusion Marketplace layout to be Image (left) and Content (right).
**DONE**

2. Diffusion of Excellence programs section
* The spacing between each section needs some clean up. As specified in the ticket, please remove all of the "wonky" custom, non-uswds classes. That includes the margins by percentages. Such as, ".margin-top-8p", "margin-top-m26p" and replace with UWDS margin classes.
**DONE**

* Double check spacing for tablet and mobile devices as the current margins are too small and doesn't allow for clarity as far as to when a section ends and the next begins.
**DONE**

3. Diffusion Academy needs some cleaning up. The lop sided section just does not flow with the rest of the page.
* I have created a mockup for this section. This will be for tablet-lg and up tablet and down will be stacked.
**DONE**


4. News and Events section is missing the new articles.
**DONE**


Layout Updates that currently exist
1. I do not know why this blue section extends past the USWDS container but let's fix that. Make the blue container fit within the ".grid-container".
**DONE**


2. Hopefully this is a product from above but on desktop/tablet-lg the blue section is smaller than the USWDS container. Let's fix that.
**DONE**


3. On "tablet-lg", I am not a fan of how tiny these images are. Please make the sections span 100% of the width on "tablet-lg" and down.
**DONE**

4. Please double check that there is just ONE h1 on the page. That should be "Replicating and Scaling Promising Practices". All the other h1's need to h2 with the ".h1" class attached for font size. Thank you.
**DONE**

**Review by will-bbg — CHANGES_REQUESTED** [review]
Great work, Ryan. Thank you.

I have one more small edit. On the "#doe-programs" element please do the following:
- remove the width
- add a border-radius of 8px
- remove all margins

**Comment by RyanCrux** [comment]
#doe-programs edits:
- remove the width
- add a border-radius of 8px
- remove all margins
DONE

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
